
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: guests
  name: guests
  namespace: letsmeetup
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: guests
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: guests
    spec:
      containers:
      - env:
        - name: AZURE_COSMOS_DB_KEY
          valueFrom:
            secretKeyRef:
              key: AZURE_COSMOS_DB_KEY
              name: letsmeetup
        image: paulgmiller/letsmeetup:c2ade03
        imagePullPolicy: Always
        name: letsmeetup
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 300Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30