apiVersion: v1
kind: Service
metadata:
  labels:
    app: guests
  name: guests
  namespace: letsmeetup
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: guests
  sessionAffinity: None
  type: LoadBalancer